"""initial schema

Revision ID: 72356a4236c0
Revises: 
Create Date: 2026-04-21 11:21:32.478215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


# revision identifiers, used by Alembic.
revision: str = '72356a4236c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('event_code', sa.String(length=20), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=50), nullable=True),
    sa.Column('station_count', sa.Integer(), nullable=False),
    sa.Column('overlay_config', sa.JSON(), nullable=True),
    sa.Column('memo', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_table('obs_presets',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('obs_host', sa.String(length=100), nullable=True),
    sa.Column('obs_port', sa.Integer(), nullable=False),
    sa.Column('obs_password', sa.String(length=200), nullable=True),
    sa.Column('youtube_stream_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_stream_key', sa.String(length=200), nullable=True),
    sa.Column('youtube_offset_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('operation_sessions',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('event_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('competition_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('event_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('event_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_code', sa.String(length=30), nullable=True),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('heat_duration_sec', sa.Integer(), nullable=False),
    sa.Column('participants_per_heat', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('competition_date', sa.Date(), nullable=True),
    sa.Column('heat_assignments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('event_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('station_number', sa.Integer(), nullable=False),
    sa.Column('obs_host', sa.String(length=100), nullable=True),
    sa.Column('obs_port', sa.Integer(), nullable=False),
    sa.Column('obs_password', sa.String(length=200), nullable=True),
    sa.Column('youtube_stream_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_stream_key', sa.String(length=200), nullable=True),
    sa.Column('youtube_offset_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'CONNECTING', 'STREAMING', 'ERROR', name='stationstatus'), nullable=False),
    sa.Column('recording_path', sa.String(length=500), nullable=True),
    sa.Column('recording_started_at', sa.DateTime(), nullable=True),
    sa.Column('stream_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heats',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('station_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('heat_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('youtube_timestamp', sa.String(length=20), nullable=True),
    sa.Column('youtube_link', sa.String(length=200), nullable=True),
    sa.Column('clip_path', sa.String(length=500), nullable=True),
    sa.Column('clip_url', sa.String(length=500), nullable=True),
    sa.Column('clip_status', sa.String(length=20), nullable=True),
    sa.Column('recording_offset_start', sa.Float(), nullable=True),
    sa.Column('recording_offset_end', sa.Float(), nullable=True),
    sa.Column('obs_timecode_start', sa.Float(), nullable=True),
    sa.Column('obs_timecode_end', sa.Float(), nullable=True),
    sa.Column('obs_stream_timecode_start', sa.Float(), nullable=True),
    sa.Column('obs_stream_timecode_end', sa.Float(), nullable=True),
    sa.Column('program_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('session_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='heatstatus'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['operation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heat_participants',
    sa.Column('heat_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('participant_id', app.core.types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['heat_id'], ['heats.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('heat_id', 'participant_id')
    )
    op.create_table('notifications',
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('heat_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('participant_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'KAKAO', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['heat_id'], ['heats.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('heat_participants')
    op.drop_table('heats')
    op.drop_table('stations')
    op.drop_table('programs')
    op.drop_table('participants')
    op.drop_table('operation_sessions')
    op.drop_table('users')
    op.drop_table('obs_presets')
    op.drop_table('events')
    # ### end Alembic commands ###
